# Generated by Django 4.1.5 on 2023-01-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_instructions', models.TextField(blank=True, null=True)),
                ('recipe_picture', models.ImageField(blank=True, upload_to='resepti/')),
                ('recipe_visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('recipe_count', models.IntegerField(default=0)),
                ('class_visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('recipe_unit_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ingredient_amount', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tables', to='recipe.recipe')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tables', to='recipe.recipeingredient')),
                ('recipe_ingredient_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tables', to='recipe.recipeunit')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to='recipe.recipeclass'),
        ),
    ]
