# Generated by Django 4.1.5 on 2023-01-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient']},
        ),
    ]
