# Generated by Django 4.1.5 on 2023-01-06 23:04

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_picture',
            field=models.ImageField(blank=True, upload_to=recipe.models.upload_picture),
        ),
    ]
