# Generated by Django 4.1.5 on 2023-01-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_recipeclass_recipe_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
