# Generated by Django 4.1.5 on 2023-01-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_rename_recipe_unit_name_recipeunit_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetable',
            old_name='recipe_ingredient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipetable',
            old_name='recipe_ingredient_amount',
            new_name='ingredient_amount',
        ),
        migrations.RenameField(
            model_name='recipetable',
            old_name='recipe_ingredient_unit',
            new_name='ingredient_unit',
        ),
    ]
