# Generated by Django 4.1.5 on 2023-01-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_rename_recipe_ingredient_recipetable_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeclass',
            old_name='class_visibility',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='recipeclass',
            old_name='class_name',
            new_name='name',
        ),
    ]
