# Generated by Django 4.1.5 on 2023-01-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_rename_recipe_instructions_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='Ingredient',
        ),
    ]
