# Generated by Django 4.1.5 on 2023-01-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_rename_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeUnit',
            new_name='IngredientUnit',
        ),
    ]
