# Generated by Django 5.0.2 on 2024-02-21 17:34

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
